name: test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #UTC
  push:
    branches:
      - 'v1'

jobs:
  composer:
    uses: kawax/composer-workflow/.github/workflows/update.yml@0d528b20aaae5c4505d0db0c4108354d57c47bf9 # v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      php: 8.5
      git-name: kawax
      git-email: 1502086+kawax@users.noreply.github.com
      composer-path: ./composer
      branch: composer-update-v1
